name: Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint-check:
    # ビルドしないと ESLint TS が型を読めずエラーになるので、ビルド後に実行する
    needs: build
    name: Lint Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup node, pnpm, turbo
        uses: ./.github/actions/check-commons
      - name: Build
        run: pnpm build
        working-directory: packages/markdown-processor
      - name: Lint
        run: pnpm lint:check

  format-check:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup node, pnpm, turbo
        uses: ./.github/actions/check-commons
      - name: Format
        run: pnpm format:check

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup node, pnpm, turbo
        uses: ./.github/actions/check-commons
      - name: Test
        run: pnpm test

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup node, pnpm, turbo
        uses: ./.github/actions/check-commons
      - name: Build
        run: pnpm build
        working-directory: packages/markdown-processor

  example-build:
    name: Example Build
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        example:
          - next-js-blog
          - react-router-blog-on-cloudflare
    steps:
      - name: Checkout Repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup node, pnpm, turbo
        uses: ./.github/actions/check-commons
      - name: Build Package
        run: pnpm build
        working-directory: packages/markdown-processor
      - name: Build
        run: pnpm build
        working-directory: examples/${{ matrix.example }}
