name: Check Workflow Common Steps
description: check workflow に使われている共通処理をまとめたもの

runs:
  using: composite
  steps:
    - name: Launch Turbo Remote Cache Server
      uses: rharkor/caching-for-turbo@2b4b5b14a8d16b8556a58993a8ac331d56d8906d # v2.3.2
      with:
        cache-prefix: turbogha_

    - name: Install pnpm
      uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0

    - name: Setup Node.js 22.x
      uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
      with:
        node-version: 22.x
        cache: pnpm

    - name: Install Dependencies
      shell: bash
      run: pnpm install --frozen-lockfile --prefer-offline
