name: Check Workflow Common Steps
description: check workflow に使われている共通処理をまとめたもの

runs:
  using: composite
  steps:
    - name: Checkout Repo
      uses: actions/checkout@v5

    - name: Launch Turbo Remote Cache Server
      uses: rharkor/caching-for-turbo@v2.3.2
      with:
        cache-prefix: turbogha_

    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Setup Node.js 22.x
      uses: actions/setup-node@v5
      with:
        node-version: 22.x
        cache: pnpm

    - name: Install Dependencies
      run: pnpm install --frozen-lockfile --prefer-offline
